spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/audit_db
    username: audit_user
    password: audit_pass

  jpa:
    show-sql: true

jwt:
  secret: changeme-this-is-a-very-long-dev-secret-key-32chars