apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  namespace: university-platform
  labels:
    app: postgres-auth
    part-of: university-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: university-platform
  labels:
    app: postgres-auth
    part-of: university-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
        part-of: university-platform
    spec:
      containers:
        - name: postgres-auth
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "auth_db"
            - name: POSTGRES_USER
              value: "auth_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: university-secrets
                  key: auth-db-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: university-platform
  labels:
    app: postgres-auth
    part-of: university-platform
spec:
  type: ClusterIP
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
